build:
  image: golang
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    registry: registry.polygon.duckdns.org:5000
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: gceme
    tag:
      - latest
      - $$TAG
    when:
      event: tag
