build:
  image: golang
  commands:
    - go get -d -v
    - go test

publish:
  docker:
    registry: registry.polygon.duckdns.org:5000
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    repo: gceme
    tag:
      - latest
      - $$TAG
    when:
      event: tag
